[project]
name = "currentkoi"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.2",
    "django-allauth>=65.19.7",
    "django-environ>=0.14.0",
    "django-lifecycle>=1.3.0",
    "django-ninja-extra>=0.31.7",
    "psycopg[binary]>=3.3.6",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = []


[tool.ruff]
exclude = [
    "*/migrations/*.py",
]
[lint]
select = ["I","RUF"]
