# Generated by Django 6.1.1 on 2026-10-06 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_ping_connectionsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_ping',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
